#%RAML 0.8
baseUri: http://mocksvc.mulesoft.com/mocks/744d02d1-50a6-41cb-88a0-b99faa9c7615
title: findwords
version: 1

schemas:
 - catalog: !include catalog.schema
 - document: !include document.schema
 - pages: !include pages.schema
   
resourceTypes:
  - read_only_collection:
      description: Collection of available <<resourcePathName>> in service.
      get:
        description: Get a list of <<resourcePathName>>.
        responses:
          200:
            body:
              application/json:
                example: |
                  <<example_collection>>
          204:
            description: not content  
  - item:
      description: Detail of <<resourcePathName>> .
      get:
        description: Get a list of <<resourcePathName>>.
        responses:
          200:
            body:
              application/json:
                schema: <<schema_item>>
                example: |
                  <<example_item>>
          204:
            description: not content                 
/catalogs:
  type: 
    read_only_collection:
      example_collection: !include catalogs.sample
  /{catalog_id}:
    type:
      item:
        schema_item: catalog
        example_item: !include catalog.sample
    /documents:
      type: 
        read_only_collection:
          example_collection: !include documents.sample
      /{document_id}:
        type:
          item:
            schema_item: document
            example_item: !include document.sample                   
        /pages:
          type: 
            read_only_collection:
              example_collection: !include pages.sample
          get:
            queryParameters:
                contains:
                  description: pages with this word or sentence
                  type: string
                  required: false